using GameX.Database.Type;
using System.Collections.Generic;

namespace GameX.Database.Content
{
    public class HotkeyContent
    {
        public static List<Hotkey> GetCollection()
        {
            return new List<Hotkey>
            {
                new Hotkey("Escape", 27, "escape"),
                new Hotkey("Space", 32, "space"),
                new Hotkey("F1", 112, "f1"),
                new Hotkey("F2", 113, "f2"),
                new Hotkey("F3", 114, "f3"),
                new Hotkey("F4", 115, "f4"),
                new Hotkey("F5", 116, "f5"),
                new Hotkey("F6", 117, "f6"),
                new Hotkey("F7", 118, "f7"),
                new Hotkey("F8", 119, "f8"),
                new Hotkey("F9", 120, "f9"),
                new Hotkey("F10", 121, "f10"),
                new Hotkey("F11", 122, "f11"),
                new Hotkey("F12", 123, "f12"),
                new Hotkey("A", 65, "a"),
                new Hotkey("B", 66, "b"),
                new Hotkey("C", 67, "c"),
                new Hotkey("D", 68, "d"),
                new Hotkey("E", 69, "e"),
                new Hotkey("F", 70, "f"),
                new Hotkey("G", 71, "g"),
                new Hotkey("H", 72, "h"),
                new Hotkey("I", 73, "i"),
                new Hotkey("J", 74, "j"),
                new Hotkey("K", 75, "k"),
                new Hotkey("L", 76, "l"),
                new Hotkey("M", 77, "m"),
                new Hotkey("N", 78, "n"),
                new Hotkey("O", 79, "o"),
                new Hotkey("P", 80, "p"),
                new Hotkey("Q", 81, "q"),
                new Hotkey("R", 82, "r"),
                new Hotkey("S", 83, "s"),
                new Hotkey("T", 84, "t"),
                new Hotkey("U", 85, "u"),
                new Hotkey("V", 86, "v"),
                new Hotkey("W", 87, "w"),
                new Hotkey("X", 88, "x"),
                new Hotkey("Y", 89, "y"),
                new Hotkey("Z", 90, "z"),
                new Hotkey("0", 48, "0"),
                new Hotkey("1", 49, "1"),
                new Hotkey("2", 50, "2"),
                new Hotkey("3", 51, "3"),
                new Hotkey("4", 52, "4"),
                new Hotkey("5", 53, "5"),
                new Hotkey("6", 54, "6"),
                new Hotkey("7", 55, "7"),
                new Hotkey("8", 56, "8"),
                new Hotkey("9", 57, "9"),
                new Hotkey("-", 189, "separator"),
                new Hotkey("=", 187, "equals"),
                new Hotkey("[", 219, "open-bracket"),
                new Hotkey("]", 221, "close-bracket"),
                new Hotkey("\\", 220, "path"),
                new Hotkey(";", 186, "semicolon"),
                new Hotkey("'", 222, "apostrophe"),
                new Hotkey(",", 188, "comma"),
                new Hotkey(".", 190, "dot"),
                new Hotkey("/", 191, "divide"),
                new Hotkey("`", 192, "apostrophe"),
                new Hotkey("Numpad 0", 96, "0"),
                new Hotkey("Numpad 1", 97, "1"),
                new Hotkey("Numpad 2", 98, "2"),
                new Hotkey("Numpad 3", 99, "3"),
                new Hotkey("Numpad 4", 100, "4"),
                new Hotkey("Numpad 5", 101, "5"),
                new Hotkey("Numpad 6", 102, "6"),
                new Hotkey("Numpad 7", 103, "7"),
                new Hotkey("Numpad 8", 104, "8"),
                new Hotkey("Numpad 9", 105, "9"),
                new Hotkey("Numpad +", 107, "+"),
                new Hotkey("Numpad -", 109, "-"),
                new Hotkey("Numpad *", 106, "empty"),
                new Hotkey("Numpad .", 110, "dot"),
                new Hotkey("Numpad /", 111, "divide"),
                new Hotkey("Numpad Enter", 13, "empty"),
                new Hotkey("Up", 38, "up"),
                new Hotkey("Down", 40, "down"),
                new Hotkey("Left", 37, "left"),
                new Hotkey("Right", 39, "right"),
            };
        }
    }
}
