using GameX.Database.Type;
using GameX.Helpers;
using GameX.Modules;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace GameX.Database.Content
{
    public class SpeechContent
    {
        public static List<Speech> GetCollection(bool WritePrefabs)
        {
            if (!WritePrefabs)
            {
                try
                {
                    DirectoryInfo Folder = new DirectoryInfo(@"addons/GameX.Biohazard.5/prefabs/speech/");
                    FileInfo[] Files = Folder.GetFiles("*.json");
                    List<Speech> Available = new List<Speech>();

                    foreach (FileInfo file in Files)
                    {
                        Available.Add(Serializer.Deserialize<Speech>(File.ReadAllText(@"addons/GameX.Biohazard.5/prefabs/speech/" + file.Name)));
                    }

                    return Available.OrderBy(x => x.Character).ToList();
                }
                catch (Exception Ex)
                {
                    Terminal.WriteLine(Ex);
                    return new List<Speech>();
                }
            }

            //TODO: Finish line texts

            Speech Chris = new Speech
            {
                Character = Enum.CharacterEnum.Chris,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("[No File]", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'd rather not...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("[No File]", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Help me out here!", 44),
                    new Simple("Help... me! (Dying)", 45),
                    new Simple("I'm not... gonna make it...! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("Much Appreciated", 50),
                    new Simple("Thanks for the help", 51),
                    new Simple("Watch yourself, okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("Stay with me!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("Nice!", 58),
                    new Simple("Good job!", 59),
                    new Simple("That'll work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Great shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("[No File]", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("Gimme your gun!", 80),
                    new Simple("Gimme your weapon!", 81),
                    new Simple("Gimme your handgun!", 82),
                    new Simple("Gimme your shotgun!", 83),
                    new Simple("Gimme your rifle!", 84),
                    new Simple("Gimme your magnum!", 85),
                    new Simple("Gimme your machinegun!", 86),
                    new Simple("Gimme your rocket launcher!", 87),
                    new Simple("I need that!", 88),
                    new Simple("Gimme an egg!", 89),
                    new Simple("Gimme a can of first aid spray!", 90),
                    new Simple("I can't hold anymore...", 91),
                    new Simple("I've got all I can hold.", 92),
                    new Simple("You hang onto it!", 93),
                    new Simple("Take it!", 94),
                    new Simple("You grab it!", 95),
                    new Simple("Gimme a hand!", 96),
                    new Simple("A little help?", 97),
                    new Simple("You go", 98),
                    new Simple("After you", 99)
                }
            };

            Speech Sheva = new Speech
            {
                Character = Enum.CharacterEnum.Sheva,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("Chris", 10),
                    new Simple("[No File]", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Come with me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok!", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("You can't be serious.", 23),
                    new Simple("Forget it!", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("Chris!", 37),
                    new Simple("[No File]", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry Up!", 42),
                    new Simple("Help me!", 43),
                    new Simple("I need your help!", 44),
                    new Simple("Uh... a help! (Dying)", 45),
                    new Simple("I need... help! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("I own you one!", 50),
                    new Simple("Thanks partner!", 51),
                    new Simple("You need to be careful!", 52),
                    new Simple("Are you OK?", 53),
                    new Simple("Don't be reckless.", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("That's good!", 58),
                    new Simple("Excellent!", 59),
                    new Simple("Nice teamwork!", 60),
                    new Simple("Chou ben deza 😨", 61),
                    new Simple("Nice shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("Chris!!! (Partner died)", 67),
                    new Simple("[No File]", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("Kunanini 😈", 71),
                    new Simple("Shit!", 72),
                    new Simple("Uhht...", 73),
                    new Simple("Morvy?", 74),
                    new Simple("???", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("I need you gun!", 80),
                    new Simple("I need your weapon!", 81),
                    new Simple("I need your handgun!", 82),
                    new Simple("I need your shotgun!", 83),
                    new Simple("I need your rifle!", 84),
                    new Simple("I need your magnum!", 85),
                    new Simple("I need your machinegun!", 86),
                    new Simple("I need your rocket launcher!", 87),
                    new Simple("Can I have that?", 88),
                    new Simple("I need an egg!", 89),
                    new Simple("I need a can of first aid spray!", 90),
                    new Simple("I can't hold anything else.", 91),
                    new Simple("I got all I can carry!", 92),
                    new Simple("You keep it!", 93),
                    new Simple("You can have it!", 94),
                    new Simple("You take that!", 95),
                    new Simple("This is a job for you!", 96),
                    new Simple("I need your assistance!", 97),
                    new Simple("You should go!", 98),
                    new Simple("Take this across!", 99)
                }
            };

            Speech Jill = new Speech
            {
                Character = Enum.CharacterEnum.Jill,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("Chris", 10),
                    new Simple("Sheva", 11),
                    new Simple("[No File]", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'm gonna say no...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("I need an herb!", 30),
                    new Simple("Hand me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("Chris", 37),
                    new Simple("Sheva!", 38),
                    new Simple("[No File]", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help me!", 43),
                    new Simple("Give me a hand!", 44),
                    new Simple("Uhh... help me! (Dying)", 45),
                    new Simple("Need... help... (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("I owe you one", 50),
                    new Simple("You bailed me out back there!", 51),
                    new Simple("Be more careful okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("You gotta be careful!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("That's good!", 58),
                    new Simple("Yes!!!", 59),
                    new Simple("Good work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Nice one!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("Chris!!! (Partner died)", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("[No File]", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Uhht...", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("I need your gun!", 80),
                    new Simple("I need your weapon!", 81),
                    new Simple("I need your handgun!", 82),
                    new Simple("I need your shotgun!", 83),
                    new Simple("I need your rifle!", 84),
                    new Simple("I need your magnum!", 85),
                    new Simple("I need your machinegun!", 86),
                    new Simple("I need your rocket launcher!", 87),
                    new Simple("Can I have that?", 88),
                    new Simple("I need an egg!", 89),
                    new Simple("I need a can of first aid spray!", 90),
                    new Simple("Sorry, I can't hold anymore!", 91),
                    new Simple("I can't carry anymore!", 92),
                    new Simple("Just, hold onto it for now.", 93),
                    new Simple("You take it!", 94),
                    new Simple("Pick it up!", 95),
                    new Simple("Help me out here!", 96),
                    new Simple("Can you take care of this?", 97),
                    new Simple("You go! I'll watch your back!", 98),
                    new Simple("Go ahead! I'll hang back!", 99)
                }
            };

            Speech Wesker = new Speech
            {
                Character = Enum.CharacterEnum.Wesker,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("[No File]", 6),
                    new Simple("[No File]", 7),
                    new Simple("[No File]", 8),
                    new Simple("[No File]", 9),
                    new Simple("Chris", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("[No File]", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("You may investigate on your own.", 18),
                    new Simple("Affirmative!", 19),
                    new Simple("Fine.", 20),
                    new Simple("I'll handle this.", 21),
                    new Simple("Impossible!", 22),
                    new Simple("Don't make me laugh!", 23),
                    new Simple("I think not!", 24),
                    new Simple("Don't expect me to give you directions!", 25),
                    new Simple("You have my permission to move about freely!", 26),
                    new Simple("Wait!", 27),
                    new Simple("[No File]", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("I need a grenade!", 31),
                    new Simple("Here!", 32),
                    new Simple("Take this!", 33),
                    new Simple("[No File]", 34),
                    new Simple("[No File]", 35),
                    new Simple("[No File]", 36),
                    new Simple("Chris!", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("[No File]", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Your assistance is required!", 44),
                    new Simple("How is this possible?! (Dying)", 45),
                    new Simple("You failed me! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("It was in your best interest to assist me!", 49),
                    new Simple("I supposed I should thank you.", 50),
                    new Simple("Ha!", 51),
                    new Simple("Be more careful!", 52),
                    new Simple("Don't be so careless!", 53),
                    new Simple("Don't get sloppy!", 54),
                    new Simple("[No File]", 55),
                    new Simple("[No File]", 56),
                    new Simple("[No File]", 57),
                    new Simple("You're getting better!", 58),
                    new Simple("Not bad.", 59),
                    new Simple("Good team work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Impressive!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("[No File]", 65),
                    new Simple("Reload!", 66),
                    new Simple("Worthless! (Partner died)", 67),
                    new Simple("Pathetic! (Partner died)", 68),
                    new Simple("Incompetence Surrounds me! (Partner died)", 69),
                    new Simple("[No File]", 70),
                    new Simple("[No File]", 71),
                    new Simple("Ah Shit!", 72),
                    new Simple("Argh... tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("[No File]", 79),
                    new Simple("I require your gun!", 80),
                    new Simple("I require your weapon!", 81),
                    new Simple("I require your handgun!", 82),
                    new Simple("I require your shotgun!", 83),
                    new Simple("I require your rifle!", 84),
                    new Simple("I require your magnum!", 85),
                    new Simple("I require your machinegun!", 86),
                    new Simple("I require your rocket launcher!", 87),
                    new Simple("Give that to me!", 88),
                    new Simple("You will give me an egg!", 89),
                    new Simple("You will give me a can of first aid spray!", 90),
                    new Simple("I have all that I need!", 91),
                    new Simple("Out of the question!", 92),
                    new Simple("It's your baggage.", 93),
                    new Simple("You may have it.", 94),
                    new Simple("Pick that up!", 95),
                    new Simple("Take care of this.", 96),
                    new Simple("I'll leave this to you.", 97),
                    new Simple("I'm sending you!", 98),
                    new Simple("Go across, now!", 99)
                }
            };

            Speech Josh = new Speech
            {
                Character = Enum.CharacterEnum.Josh,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("[No File]", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'd rather not...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("[No File]", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Help me out here!", 44),
                    new Simple("Help... me! (Dying)", 45),
                    new Simple("I'm not... gonna make it...! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("Much Appreciated", 50),
                    new Simple("Thanks for the help", 51),
                    new Simple("Watch yourself, okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("Stay with me!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("Nice!", 58),
                    new Simple("Good job!", 59),
                    new Simple("That'll work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Great shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("[No File]", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("Gimme your gun!", 80),
                    new Simple("Gimme your weapon!", 81),
                    new Simple("Gimme your handgun!", 82),
                    new Simple("Gimme your shotgun!", 83),
                    new Simple("Gimme your rifle!", 84),
                    new Simple("Gimme your magnum!", 85),
                    new Simple("Gimme your machinegun!", 86),
                    new Simple("Gimme your rocket launcher!", 87),
                    new Simple("I need that!", 88),
                    new Simple("Gimme an egg!", 89),
                    new Simple("Gimme a can of first aid spray!", 90),
                    new Simple("I can't hold anymore...", 91),
                    new Simple("I've got all I can hold.", 92),
                    new Simple("You hang onto it!", 93),
                    new Simple("Take it!", 94),
                    new Simple("You grab it!", 95),
                    new Simple("Gimme a hand!", 96),
                    new Simple("A little help?", 97),
                    new Simple("You go", 98),
                    new Simple("After you", 99)
                }
            };

            Speech Excella = new Speech
            {
                Character = Enum.CharacterEnum.Excella,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("[No File]", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'd rather not...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("[No File]", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Help me out here!", 44),
                    new Simple("Help... me! (Dying)", 45),
                    new Simple("I'm not... gonna make it...! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("Much Appreciated", 50),
                    new Simple("Thanks for the help", 51),
                    new Simple("Watch yourself, okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("Stay with me!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("Nice!", 58),
                    new Simple("Good job!", 59),
                    new Simple("That'll work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Great shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("[No File]", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("Gimme your gun!", 80),
                    new Simple("Gimme your weapon!", 81),
                    new Simple("Gimme your handgun!", 82),
                    new Simple("Gimme your shotgun!", 83),
                    new Simple("Gimme your rifle!", 84),
                    new Simple("Gimme your magnum!", 85),
                    new Simple("Gimme your machinegun!", 86),
                    new Simple("Gimme your rocket launcher!", 87),
                    new Simple("I need that!", 88),
                    new Simple("Gimme an egg!", 89),
                    new Simple("Gimme a can of first aid spray!", 90),
                    new Simple("I can't hold anymore...", 91),
                    new Simple("I've got all I can hold.", 92),
                    new Simple("You hang onto it!", 93),
                    new Simple("Take it!", 94),
                    new Simple("You grab it!", 95),
                    new Simple("Gimme a hand!", 96),
                    new Simple("A little help?", 97),
                    new Simple("You go", 98),
                    new Simple("After you", 99)
                }
            };

            Speech Barry = new Speech
            {
                Character = Enum.CharacterEnum.Barry,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("[No File]", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'd rather not...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("[No File]", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Help me out here!", 44),
                    new Simple("Help... me! (Dying)", 45),
                    new Simple("I'm not... gonna make it...! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("Much Appreciated", 50),
                    new Simple("Thanks for the help", 51),
                    new Simple("Watch yourself, okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("Stay with me!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("Nice!", 58),
                    new Simple("Good job!", 59),
                    new Simple("That'll work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Great shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("[No File]", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("Gimme your gun!", 80),
                    new Simple("Gimme your weapon!", 81),
                    new Simple("Gimme your handgun!", 82),
                    new Simple("Gimme your shotgun!", 83),
                    new Simple("Gimme your rifle!", 84),
                    new Simple("Gimme your magnum!", 85),
                    new Simple("Gimme your machinegun!", 86),
                    new Simple("Gimme your rocket launcher!", 87),
                    new Simple("I need that!", 88),
                    new Simple("Gimme an egg!", 89),
                    new Simple("Gimme a can of first aid spray!", 90),
                    new Simple("I can't hold anymore...", 91),
                    new Simple("I've got all I can hold.", 92),
                    new Simple("You hang onto it!", 93),
                    new Simple("Take it!", 94),
                    new Simple("You grab it!", 95),
                    new Simple("Gimme a hand!", 96),
                    new Simple("A little help?", 97),
                    new Simple("You go", 98),
                    new Simple("After you", 99)
                }
            };

            Speech Rebecca = new Speech
            {
                Character = Enum.CharacterEnum.Rebecca,
                Lines = new List<Simple>
                {
                    new Simple("[NONE]", 0),
                    new Simple("Josh", 6),
                    new Simple("Barry", 7),
                    new Simple("Rebecca", 8),
                    new Simple("Excella", 9),
                    new Simple("[No File]", 10),
                    new Simple("Sheva", 11),
                    new Simple("Jill", 12),
                    new Simple("Wesker", 13),
                    new Simple("This way!", 14),
                    new Simple("Follow me!", 15),
                    new Simple("Go!", 16),
                    new Simple("Split up!", 17),
                    new Simple("Fan out!", 18),
                    new Simple("Roger.", 19),
                    new Simple("Ok.", 20),
                    new Simple("Leave it to me.", 21),
                    new Simple("I can't right now!", 22),
                    new Simple("Out of the question!", 23),
                    new Simple("I'd rather not...", 24),
                    new Simple("Scope out the area!", 25),
                    new Simple("We can cover more ground separately!", 26),
                    new Simple("Wait!", 27),
                    new Simple("Josh", 28),
                    new Simple("I need ammo!", 29),
                    new Simple("Gimme an herb!", 30),
                    new Simple("Give me a grenade!", 31),
                    new Simple("Use this!", 32),
                    new Simple("Take this!", 33),
                    new Simple("Barry!", 34),
                    new Simple("Rebecca!", 35),
                    new Simple("Excella!", 36),
                    new Simple("[No File]", 37),
                    new Simple("Sheva!", 38),
                    new Simple("Jill!", 39),
                    new Simple("Wesker!", 40),
                    new Simple("Come on!", 41),
                    new Simple("Hurry!", 42),
                    new Simple("Help!", 43),
                    new Simple("Help me out here!", 44),
                    new Simple("Help... me! (Dying)", 45),
                    new Simple("I'm not... gonna make it...! (Dying)", 46),
                    new Simple("I'm coming! (Partner Dying)", 47),
                    new Simple("Hold on! (Partner Dying)", 48),
                    new Simple("Thanks.", 49),
                    new Simple("Much Appreciated", 50),
                    new Simple("Thanks for the help", 51),
                    new Simple("Watch yourself, okay?", 52),
                    new Simple("You okay?", 53),
                    new Simple("Stay with me!", 54),
                    new Simple("Josh!!! (Partner died)", 55),
                    new Simple("Barry!!! (Partner died)", 56),
                    new Simple("Rebecca!!! (Partner died)", 57),
                    new Simple("Nice!", 58),
                    new Simple("Good job!", 59),
                    new Simple("That'll work!", 60),
                    new Simple("[No File]", 61),
                    new Simple("Great shot!", 62),
                    new Simple("Good work!", 63),
                    new Simple("Nice work!", 64),
                    new Simple("Excella!!! (Partner died)", 65),
                    new Simple("Reload!", 66),
                    new Simple("[No File]", 67),
                    new Simple("Sheva!!! (Partner died)", 68),
                    new Simple("Jill!!! (Partner died)", 69),
                    new Simple("Wesker!!! (Partner died)", 70),
                    new Simple("[No File]", 71),
                    new Simple("Shit!", 72),
                    new Simple("Tsc.", 73),
                    new Simple("[No File]", 74),
                    new Simple("[No File]", 75),
                    new Simple("[No File]", 76),
                    new Simple("[No File]", 77),
                    new Simple("[No File]", 78),
                    new Simple("Watch out!", 79),
                    new Simple("Gimme your gun!", 80),
                    new Simple("Gimme your weapon!", 81),
                    new Simple("Gimme your handgun!", 82),
                    new Simple("Gimme your shotgun!", 83),
                    new Simple("Gimme your rifle!", 84),
                    new Simple("Gimme your magnum!", 85),
                    new Simple("Gimme your machinegun!", 86),
                    new Simple("Gimme your rocket launcher!", 87),
                    new Simple("I need that!", 88),
                    new Simple("Gimme an egg!", 89),
                    new Simple("Gimme a can of first aid spray!", 90),
                    new Simple("I can't hold anymore...", 91),
                    new Simple("I've got all I can hold.", 92),
                    new Simple("You hang onto it!", 93),
                    new Simple("Take it!", 94),
                    new Simple("You grab it!", 95),
                    new Simple("Gimme a hand!", 96),
                    new Simple("A little help?", 97),
                    new Simple("You go", 98),
                    new Simple("After you", 99)
                }
            };

            var obj = new List<Speech>
            {
                Chris,
                Sheva,
                Jill,
                Wesker,
                Josh,
                Excella,
                Barry,
                Rebecca
            };

            try
            {
                foreach (Speech Char in obj)
                    Serializer.WriteDataFile(@"addons/GameX.Biohazard.5/prefabs/speech/" + $"{Char.Character.ToString().ToLower()}.json", Serializer.Serialize(Char));

                Terminal.WriteLine("[App] Speech prefabs written sucessfully.");
            }
            catch (Exception Ex)
            {
                Terminal.WriteLine(Ex);
            }

            return obj;
        }
    }
}
